- name: Create Awesome Badge
  uses: schneegans/dynamic-badges-action@v1.0.0
  with:
    auth: ${{ secrets.BADGE_SECRET }}
    gistID: <gist-ID>
    filename: test.json
    label: Hello
    message: World
    color: orange
